#######
# Compiled from mdgame/functions/machines/conveyour.mcscript
# to .//data/mdgame/functions/machines/machines/conveyour.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=north] run tp @s[type=player] ~ ~ ~0.05
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=north] run data merge entity @s[type=!player] {Motion:[0.0,-0.8,0.05]}
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=south] run tp @s[type=player] ~ ~ ~-0.05
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=south] run data merge entity @s[type=!player] {Motion:[0.0,-0.8,-0.1]}
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=west] run tp @s[type=player] ~0.05 ~ ~
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=west] run data merge entity @s[type=!player] {Motion:[0.05,-0.8,0.0]}
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=east] run tp @s[type=player] ~-0.05 ~ ~
execute as @e at @s if block ~ ~-1 ~ magenta_glazed_terracotta[facing=east] run data merge entity @s[type=!player] {Motion:[-0.05,-0.8,0.0]}