#######
# Compiled from data/mdgame/functions/load.mcscript
# to .//data/mdgame/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
e compiler!
scoreboard objectives add itemcounts dummy

# Extended from data/mdgame/functions/load.mcscript
# to data/mdgame/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add MachineTick dummy
