#######
# Compiled from data/mdgame/functions/load.mcscript
# to .//data/mdgame/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

# Extended from data/mdgame/functions/load.mcscript
# to data/mdgame/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add MachineTick dummy

# Extended from functions/machines/miners/copperminer.mcscript
# to data/mdgame/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add T1MiningSpeed dummy
scoreboard objectives add calcTick dummy

# Extended from mdgame/functions/utility/dropitem.mcscript
# to data/mdgame/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add itemcounts dummy
