#######
# Compiled from data/mdgame/functions/conveyour.mcscript
# to .//data/mdgame/functions/convey.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/mdgame/functions/conveyour.mcscript
run:tp @s[type=player] ~$(tpDirX) ~ ~$(tpDirZ)
run:data merge entity @s[type=!player] {Motion:[$(tpDirX),-0.8,$(tpDirZ)]}