#######
# Compiled from functions/machines/machine_placers/p_copperminer.mcscript
# to .//data/mdgame/functions/machines/machine_placers/p_copper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
