#######
# Compiled from functions/machines/machine_placers/p_copperminer.mcscript
# to .//data/mdgame/functions/machines/machine_placers/p_copper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:white_glazed_terracotta
setblock ~ ~1 ~ minecraft:dropper[facing=down]
summon minecraft:armor_stand ~ ~1 ~ {Marker:1b,Invisible:1b,NoGravity:1b,CustomName:"\"T1Miner\""}
kill @s