#######
# Compiled from functions/machines/machine_placers/p_outputter.mcscript
# to .//data/mdgame/functions/machines/machine_placers/p_outputter.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:torch
summon minecraft:armor_stand ~ ~ ~ {CustomName:"\"output1\"", Marker:1b, Invisible:1b}
kill @s