#######
# Compiled from functions/machines/machine_placers/p_outputter.mcscript
# to .//data/mdgame/functions/machines/machine_placers/p_outputter.mcfunction
#
# Generated by Minecraft Script for 1.13
######
