#######
# Compiled from mdgame/functions/machines/outputter.mcscript
# to .//data/mdgame/functions/machines/outputter.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ air run kill @s
