#######
# Compiled from functions/machines/miners/copperminer.mcscript
# to .//data/mdgame/functions/machines/miners/copper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set T1MiningSpeed T1MiningSpeed 20
scoreboard players set calcTick calcTick 0
scoreboard players operation calcTick calcTick = MachineTick MachineTick
scoreboard players operation calcTick calcTick %= T1MiningSpeed T1MiningSpeed
execute if score calcTick calcTick matches 0 if block ~ ~-2 ~ #mdgame:coppertier run loot insert ~ ~ ~ mine ~ ~-2 ~
