#######
# Compiled from functions/machines/miners/copperminer.mcscript
# to .//data/mdgame/functions/machines/miners/copper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~-2 ~ #mdgame:coppertier run loot insert ~ ~ ~ mine ~ ~-2 ~
