#######
# Compiled from functions/machines/miners/copperminer.mcscript
# to .//data/mdgame/functions/machines/miners/machines/miners/copper.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"test","color":"white"}]